### ISSUE TITLE
No way to close a project and start another

### ISSUE THREAD

**Issue by rishabhkesarwani** [materiahq/materia-designer-public#64] opened 2016-10-26 20:53 UTC
### Current behavior

Right now there is no option to close the project and start another.

### Expected behavior

Expecting to be a option of close project.

### Step to reproduce the behavior

* Create a project.
* Delete project files manually and open the application => The application will stuck in the project and there is no way we can close the project or switch to another project.

---

- OS Platform / arch: MacOS
- Database : MySQL / PostgreSQL / SQLite
- Materia Server Version: 0.3.2
- Materia Designer Version: 0.3.2

**Comment by thyb** [comment] 2016-10-26 21:54
You can change the project with the icon on the top left corner:

![change application gif](https://getmateria.com/img/gif/app-swap.gif?cache=1477518341504)

In your application list, you can click the "+" icon in the bottom left corner to create new application/project.

To remove a project, you can go in the "application settings" in the "admin" tab, you have a big button "remove this application"

![screen shot 2016-10-26 at 5 52 26 pm](https://cloud.githubusercontent.com/assets/1288646/19746567/fc78f9ea-9ba4-11e6-8a23-fee64d1df036.png)

**Comment by thyb** [comment] 2016-10-26 22:03
BTW, There is an existing bug (#49) when you rename or remove manually the application folder opened in Materia. In the following [comment](https://github.com/webshell/materia-designer/issues/49#issuecomment-246889533), there is 2 workarounds for this bug meanwhile we fix it

**Comment by thyb** [comment] 2016-11-01 05:30
I close this issue as it seems to be a duplicate of #49.

**Closed as completed by thyb** 2016-11-01 05:30 UTC
Labels: type/duplicate, area/applications
